### ISSUE TITLE
Font Awesome icons not displayed when https is not used

### ISSUE THREAD

**Issue by roylockhart** [DandyDev/pelican-bootstrap3#167]
![capture d ecran 2015-02-17 a 22 32 08](https://cloud.githubusercontent.com/assets/10902805/6237646/da0d3d94-b6f4-11e4-8af3-131ceb3a52ea.png)

If somebody also have a trick for the search form. It's stuck to the top :/

Thanks in advance !

**Comment by DandyDev** [comment]
Regarding the protocol (HTTP/HTTPS), I'm not sure what causes your problem. My site doesn't use HTTPS either, and FA icons show just fine: http://dandydev.net/
Regarding the search box, the proper size of the box depends on what Bootstrap/Bootswatch theme you use. In my particular case (I use 'simplex'), I had to add the following custom css:

```css
#tipue_search_input {
    padding: 9px 12px 9px 40px;
    background-position: 15px 13px;
}
```

Hope that helps!
