### ISSUE TITLE
code block wrapping

### ISSUE THREAD

**Issue by kpurdon** [DandyDev/pelican-bootstrap3#207]
Ideally you don't want to wrap code-block text, instead preferring horizontal scroll since formatting matters.

I solved this with CUSTOM_CSS

```css
pre {
  overflow: auto;
  word-wrap: normal;
  white-space: pre;
}
```

Perhaps this (or another solution) could be activated with a new option `CODE_OVERFLOW` or something like that.
